name: absen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_signin_button: ^2.0.0
  percent_indicator: ^4.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/frame.png
    - assets/images/profile.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/proyek.png
    - assets/images/account.png
    - assets/images/home.png
    - assets/images/notif.png
    - assets/images/task.png
    - assets/images/location.png

